nginx:
    container_name: nginx
    build: ./nginx/
    ports:
        - 80:80
        - 443:443
    links:
        - php
    volumes_from:
        - data-www

php:
    container_name: php
    build: ./php/
    expose:
        - 9000
    links:
        - mysql
    volumes_from:
        - data-www

data-www:
    container_name: data-www
    image: busybox:latest
    volumes:
        - ~/Movies/html:/var/www/html
    command: "true"

mysql:
    container_name: mysql
    image: mysql:latest
    volumes_from:
        - data-db
    environment:
        MYSQL_ROOT_PASSWORD: secret

data-db:
    container_name: data-db
    image: busybox:latest
    volumes:
        - /var/lib/mysql
    command: "true"

phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
        - 8080:8080
    links:
        - mysql
    environment:
        PMA_HOST: mysql
    command: "true"